### ISSUE TITLE
decoder input

### ISSUE THREAD

**Issue by TerryYiDa** [renqianluo/SemiNAS#1]
decoder_input is different with paper,why?
paper :decoder_input is fd(ex)
code: decoder_input = [self.sos_id] + encoder_input[:-1]

**Comment by renqianluo** [comment]
the vector representation of the architecture (ex) is passed into the decoder as the initial hidden state, rather than the input.
The decoder works in an auto-regressive way. So the input at each step is the token of last step.

**Comment by renqianluo** [comment]
@TerryYiDa 
The vector representation of the architecture (ex) is passed into the decoder as the initial hidden state, rather than the input.
In sequence-to-sequence learning, the input of the decoder at each time step is the token of last step.

**Comment by TerryYiDa** [comment]
> @TerryYiDa
> The vector representation of the architecture (ex) is passed into the decoder as the initial hidden state, rather than the input.
> In sequence-to-sequence learning, the input of the decoder at each time step is the token of last step.

I understand it, thanks.
