### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Escapist-Wu** [renqianluo/SemiNAS#4]
1、执行tts的 search_for_low_resource.sh demo，在22个epoch时 CUDA out of memeory。超参没有任何修改。4 gpu, 每个gpu 16g。请问demo需要做那些修改吗
2、将--max_tokens由默认的31250修改为21250，可以正常进行。但这应该对结果有影响。
3、你们用的gpu信息是什么

**Comment by renqianluo** [comment]
@Escapist-Wu 我们使用的gpu memory=24GB，如果cuda out of memory，可以尝试减少batch size，可能会对结果有影响（包括最终训练的时候），另外可以尝试accumate step（代码里没实现，得稍加改动），这样可以用小batch去模拟大batch

**Comment by Escapist-Wu** [comment]
@renqianluo 非常感谢你的回复。
另外有个问题想稍加探讨，在各种诸多场景尝试使用share weights的方式训练supernet来获取结构-精度。但正如你们论文所说，这种方式很不稳定，和真实排序相关性可能很差，导致真正的搜索很可能基于了一个不靠谱的结果。但是尽管这样，SemiNAS的初始标记数据仍选择了share weights的方式，那么后续训练predictor，NAO或者接EA仍然都要依赖于share weights的好坏。SemiNAS这种半监督的方式是否真正有效的缓解了share weights的影响？对此有一点点疑惑，希望能得到回答。

**Comment by renqianluo** [comment]
@Escapist-Wu 你好，使用weight-sharing也是考虑时间效率。目前大家研究的经验是，weight-sharing训练的时间长一些，且实际训练的结构数量少一些，会有利于缓解weight-sharing带来的负面影响。

**Comment by Escapist-Wu** [comment]
非常感谢。
